/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: StarWars-Universe (https://sketchfab.com/SWU)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/3d-models/a-wing-b13126de57c44f5388e80b411f47078e
title: A-wing
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function AWing(props) {
    const ref = useRef();

    const { nodes, materials } = useGLTF("/a-wing.glb");
    return (
        <group ref={ref} {...props} dispose={null} scale={0.02}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group rotation={[0, Math.PI / 2, 0]} scale={0.03}>
                        <group>
                            <group
                                // position={[3975.07, 712.02, -232.79]}
                                rotation={[0, -Math.PI / 2, 0]}
                                scale={32}
                            >
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1.geometry}
                                    material={materials.Hull_Dorsal}
                                />
                            </group>
                            <group position={[-126.47, -1080.58, 0]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_1.geometry}
                                    material={materials.Hull_Ventral}
                                />
                            </group>
                            <group position={[-2826.49, -633.48, 0]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_2.geometry}
                                    material={materials.Hull_Side_1}
                                />
                            </group>
                            <group position={[-1476.52, 1.72, 0]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_3.geometry}
                                    material={materials.Hull_Side_2}
                                />
                            </group>
                            <group position={[-2826.47, -820.82, -0.02]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_4.geometry}
                                    material={materials.Hull_Front}
                                />
                            </group>
                            <group position={[6191.99, 1.72, 0]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_5.geometry}
                                    material={materials.Hull_Rear}
                                />
                            </group>
                            <group position={[6114.12, 1.72, 0]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_6.geometry}
                                    material={materials.Hull_Inside}
                                />
                            </group>
                        </group>
                        <group position={[-3975.07, -712.02, 232.79]}>
                            <group position={[1199.84, 2488.31, -0.03]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_7.geometry}
                                    material={materials.Window}
                                />
                            </group>
                            <group position={[3430.06, 2487.26, -848.53]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_8.geometry}
                                    material={materials.Cockpit_Side_R}
                                />
                            </group>
                            <group position={[3430.07, 2487.26, 848.15]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_9.geometry}
                                    material={materials.Cockpit_Side_L}
                                />
                            </group>
                            <group position={[9218.43, 2504.63, -0.02]}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_10.geometry}
                                    material={materials.Cockpit_Rear}
                                />
                            </group>
                        </group>
                        <group rotation={[0, -Math.PI / 2, 0]} scale={32}>
                            <group
                                position={[7.27, 21.43, 82.45]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={0.03}
                            >
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_11.geometry}
                                    material={materials.Cockpit_Inside}
                                />
                            </group>
                            <group
                                position={[-68.44, -8.22, -131.55]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={0.03}
                            >
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_12.geometry}
                                    material={materials.Seat}
                                />
                            </group>
                            <group scale={100}>
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_13.geometry}
                                    material={materials.Pilot}
                                />
                            </group>
                        </group>
                        <group rotation={[0, -Math.PI / 2, 0]} scale={32}>
                            <group
                                position={[7.27, -17.62, 44.86]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={0.03}
                            >
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_14.geometry}
                                    material={materials.Laser}
                                />
                            </group>
                            <group
                                position={[7.27, -17.62, 44.86]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={0.03}
                            >
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_15.geometry}
                                    material={materials.Laser}
                                />
                            </group>
                            <group
                                position={[7.27, -22.25, 22.39]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={0.03}
                            >
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_16.geometry}
                                    material={materials.Laser_Holder}
                                />
                            </group>
                            <group
                                position={[7.27, -22.25, 22.39]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={0.03}
                            >
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_17.geometry}
                                    material={materials.Laser_Holder}
                                />
                            </group>
                        </group>
                        <group rotation={[0, -Math.PI / 2, 0]} scale={32}>
                            <group
                                position={[-68.44, -8.22, -131.55]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={0.03}
                            >
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_18.geometry}
                                    material={materials.Engine_L}
                                />
                            </group>
                            <group
                                position={[68.44, -8.22, -131.55]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={0.03}
                            >
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_19.geometry}
                                    material={materials.Engine_R}
                                />
                            </group>
                            <group
                                position={[7.27, -22.25, -159.58]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={0.03}
                            >
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_20.geometry}
                                    material={materials.Jet_Housing}
                                />
                            </group>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Material1_21.geometry}
                                material={materials.Jet_Rear}
                            />
                            <group
                                position={[7.27, -22.25, -159.58]}
                                rotation={[0, Math.PI / 2, 0]}
                                scale={0.03}
                            >
                                <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Material1_22.geometry}
                                    material={materials.Jet_Middle}
                                />
                            </group>
                        </group>
                        {/*<group position={[200, 0, 0]} scale={32}>*/}
                        {/*    <group position={[212.55, -21.11, 7.27]} scale={0.03}>*/}
                        {/*        <mesh*/}
                        {/*            castShadow*/}
                        {/*            receiveShadow*/}
                        {/*            geometry={nodes.Material1_23.geometry}*/}
                        {/*            material={materials.Engine_FX}*/}
                        {/*        />*/}
                        {/*    </group>*/}
                        {/*    <group position={[212.55, -21.11, 7.27]} scale={0.03}>*/}
                        {/*        <mesh*/}
                        {/*            castShadow*/}
                        {/*            receiveShadow*/}
                        {/*            geometry={nodes.Material1_24.geometry}*/}
                        {/*            material={materials.Engine_FX}*/}
                        {/*        />*/}
                        {/*    </group>*/}
                        {/*</group>*/}
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/a-wing.glb");