/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: campkb (https://sketchfab.com/campkb)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/b-wing-dbbed832945244a1865400f6f7edd1e0
title: B- Wing
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function BWing(props) {
    const ref =  useRef();

    const { nodes, materials } = useGLTF("/b-wing.glb");
    return (
        <group ref={ref} {...props} dispose={null}>
            <group
                // position={[0, 7.72, -5.01]}
                // rotation={[-Math.PI, 0, 0]}
                scale={0.5}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_2.geometry}
                    material={materials.material_0}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/b-wing.glb");
