/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Stym (https://sketchfab.com/Stym)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/3d-models/tie-bomber-7da8a4de25cb4ae5ba9b9f94c867d872
title: TIE Bomber
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function VWing(props) {
    const ref = useRef();

    const { nodes, materials } = useGLTF("/v-wing.glb");
    return (
        <group ref={ref} {...props} dispose={null} scale={3}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.M_TieBomber_01_M_TieBomber_01_0.geometry}
                        material={materials.M_TieBomber_01}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/v-wing.glb");
