/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function XWing (props) {
    const ref = useRef();
    const { nodes, materials } = useGLTF("/ship-opt.glb");

    return (
        <group ref={ref} {...props} dispose={null}>
            <group
                rotation={[-Math.PI / 2, 0, 0]}
                scale={3}
            >
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Astrodroid_mat_4_lod0_default_0.geometry}
                            material={materials["default.001"]}
                        />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes["blinn3_2_lod0_05_-_Default_0"].geometry}
                            material={materials["05_-_Default"]}
                        />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes["lambert1_0_lod0_02_-_Default_0"].geometry}
                            material={materials["02_-_Default.002"]}
                        />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes["Wings_1_lod0_03_-_Default_0"].geometry}
                            material={materials["03_-_Default"]}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/ship-opt.glb");
