/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Daniel (https://sketchfab.com/DanielAndersson)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/star-wars-y-wing-b8bb6476b1b14ba48987c7efc7b7087a
title: Star Wars: Y- Wing
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function YWing (props) {
    const ref = useRef();

    const { nodes, materials } = useGLTF("/y-wing.glb");
    return (
        <group ref={ref} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={30}>
                <group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.CockpitSectionHullPlates_0.geometry}
                        material={materials.ScratchedMetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.CockpitSectionHullPlates_1.geometry}
                        material={materials.ScratchedMetalRed}
                    />
                </group>
                <group position={[0, -0.42, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cockpit_0.geometry}
                        material={materials.ScratchedMetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cockpit_1.geometry}
                        material={materials.ReflectiveGlass}
                    />
                </group>
                <group position={[0, 0.04, 0.08]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.CockpitSection_0.geometry}
                        material={materials.ScratchedMetal}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.CockpitSection_1.geometry}
                        material={materials.ScratchedMetalDark}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.EngineBackSection_0.geometry}
                    material={materials.ScratchedMetalDark}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.EngineGreebles_0.geometry}
                    material={materials.ScratchedMetalDark}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Engines_0.geometry}
                    material={materials.ScratchedMetal}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Engines_1.geometry}
                    material={materials.YellowEngineGlow}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Engines_2.geometry}
                    material={materials.ScratchedMetalRed}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Engines_3.geometry}
                    material={materials.ScratchedMetalDark}
                />
                <group position={[0, -0.36, 0.14]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.IonCannon_0.geometry}
                        material={materials.ScratchedMetal}
                    />
                </group>
                <group position={[0, -0.36, 0.13]} rotation={[0.01, 0, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.IonCannonTurret_0.geometry}
                        material={materials.ScratchedMetal}
                    />
                </group>
                <group position={[0, -0.42, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.LaserCannon_0.geometry}
                        material={materials.ScratchedMetal}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.MainSection_0.geometry}
                    material={materials.ScratchedMetalDark}
                />
                <group position={[0, 0.04, 0.08]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.MainSectionGreebles1_0.geometry}
                        material={materials.ScratchedMetalDark}
                    />
                </group>
                <group position={[0.01, -0.19, 0.07]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.MainSectionGreebles2_0.geometry}
                        material={materials.ScratchedMetalDark}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.MainSectionHullPlates_0.geometry}
                    material={materials.ScratchedMetalDark}
                />
                <group position={[0, -0.13, 0.09]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.R2Body_0.geometry}
                        material={materials.MetalWhite}
                    />
                </group>
                <group position={[0, -0.13, 0.09]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.R2Head_0.geometry}
                        material={materials.MetalGrey}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.R2Head_1.geometry}
                        material={materials.MetalPurple}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.R2Head_2.geometry}
                        material={materials.ReflectiveGlass}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.R2Head_3.geometry}
                        material={materials.ReflectiveGlassRed}
                    />
                </group>
                <group position={[0, -0.13, 0.09]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.R2HullPlates_0.geometry}
                        material={materials.MetalWhite}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.R2HullPlates_1.geometry}
                        material={materials.MetalPurple}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.WingSection_0.geometry}
                    material={materials.ScratchedMetalDark}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.WingSectionGreebles_0.geometry}
                    material={materials.ScratchedMetalDark}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/y-wing.glb");
